version: "2"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  api_service:
    container_name: api_service
    build:
      context: api_service
    image: api_service
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      STOCK_SERVICE_URL: "http://api_service:80"
    ports:
      - "81:81"
    networks:
      - app-network

  stock_service:
    container_name: stock_service
    build:
      context: stock_service
    image: stock_service
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "81:81"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
