version: "2"
services:
  api_service:
    container_name: api_service
    build:
      context: api_service
    image: api_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Api Service"
      STOCK_SERVICE_URL: "http://stock_service:81"
      AUTH_SERVICE_URL: "http://auth_service:82"
    ports:
      - "80:80"
    networks:
      - app-network

  stock_service:
    container_name: stock_service
    build:
      context: stock_service
    image: stock_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Stock Service"
      API_SERVICE_URL: "http://stock_service:80"
    ports:
      - "81:81"
    networks:
      - app-network

  auth_service:
    container_name: auth_service
    build:
      context: auth_service
    image: auth_service
    environment:
      API_VERSION: "1.0.0"
      PROJECT_NAME: "Auth Service"
      USERNAME: "user@stock.com"
      PASSWORD: "stock_is_up_100%"
      API_SERVICE_URL: "http://stock_service:80"
    ports:
      - "82:82"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
